name: Keep Redis Alive

on:
  schedule:
    - cron: "0 */4 * * *"  

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake server
        run: |
          curl -s ${{ secrets.BACKEND_URL }}/health

      - name: Wait for server
        run: sleep 10

      - name: Hit keep-alive
        run: |
          curl -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
               -s ${{ secrets.BACKEND_URL }}/keep-alive